FROM ubuntu:xenial

RUN apt-get update && apt-get install -y wget software-properties-common && rm -rf /var/lib/apt/lists/*

WORKDIR "/root"

# Adding Ethereum repository.
RUN add-apt-repository -y ppa:ethereum/ethereum

# Installing Etheruem on the container.
ARG binary
RUN apt-get update && apt-get install -y ethereum

ARG password
ARG privatekey
RUN echo $password > ~/.accountpassword
RUN echo $privatekey > ~/.privatekey
ADD ./genesisBlock.json ./genesisBlock.json
RUN geth init genesisBlock.json
RUN geth account import --password ~/.accountpassword  ~/.privatekey

ENV address=""
ENV bootnodeId=""
ENV bootnodeIp=""

CMD exec geth --bootnodes "enode://$bootnodeId@$bootnodeIp:30301" --networkid "5" --verbosity=4 --rpc --rpcaddr "0.0.0.0" --rpcapi "eth,web3,net,admin,debug,db,personal" --rpccorsdomain "*" --syncmode="full" --etherbase $address --unlock $address --password ~/.accountpassword

EXPOSE 8545
EXPOSE 30303